<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>TerminalRearranger</AssemblyName>
    <RootNamespace>TerminalRearranger</RootNamespace>
    <ApplicationIcon Condition="Exists('app.ico')">app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <InternalsVisibleTo Include="TerminalRearranger.Checks" />
  </ItemGroup>
</Project>
